FOO:
    BAR: "BAZ"
DIRNAME: "/Users/cwilcox/Projects/piles.io"
### API Keys
CHARGIFY_API_KEY: "xxXPsiW-FGTHA6STZ6P0"
AWS_ACCESS_KEY_ID: "0Z67F08VD9JMM1WKRDR2"
AWS_SECRET_ACCESS_KEY: "g6o8NjU3ClIYJmaGurL+sKctlQrpEUF6irQyrpPX"
### App settings
# The name of the S3 bucket where the application"s user content and static files will live
APP_BUCKET: "dev.piles.io"
# The default Access Control setting for new files
APP_BUCKET_ACL: "private" #"bucket-owner-full-control"
# Bucket where logs are stored
LOG_BUCKET: "dev.piles.io-logging"
# Prefixed before all logs delivered to the above log bucket
LOG_BUCKET_PREFIX: "dev.piles.io-access-log-"
FILE_POST_URL: "http://dev.piles.io"
# The domain on which the application logic and API lives
APP_DOMAIN: "localhost:8080"
# The domain on which the application and user content lives
CONTENT_DOMAIN: "localhost:9090"
### Database settings
MONGO_HOST: "localhost"
MONGO_PORT: 27017
MONGO_DB_NAME: "piles-dev"
### Email settings
EMAIL_BOX_NAME: ""
EMAIL_BOX_PWD: ""
EMAIL_SMTP_HOST: "localhost"
EMAIL_FROM_ADDR: "robot@piles.io"
DEPLOYED: false # This should be true in the `local_settings.py` file of the API server
SECRET_KEY: "my-@wes0me_sexY_secret+key"
TEMPLATE_PATHS: ["/Users/cwilcox/Projects/piles.io/templates/"]