DEBUG: true

# The domain on which the application logic and API lives
APP_DOMAIN: "localhost:8000"
# The domain on which the content lives
STATIC_DOMAIN: "localhost:9090"
STATIC_URL: "http://localhost:9090/"
FILE_UPLOAD_URL: "http://localhost:9090/"

STATIC_BUCKET: "made-up-bucket"


TEMPLATE_PATHS: ["/Users/cwilcox/Projects/shinybox/templates/"]
RESOURCE_PATH: "/Users/cwilcox/Projects/shinybox/resources/"

STRIPE_PUBLISHABLE_KEY: "pk_I8BqRm30RrEt4EkNzzGVjobbQzVgf"  # test public key
STRIPE_SECRET_KEY: "pk_I8BqRm30RrEt4EkNzzGVjobbQzVgf" # test secret key